#-------------------------------------------------------------------------------
#  Import/Export Directories
#-------------------------------------------------------------------------------
# NOTE: All paths in this file are relative to the project directory.
#-------------------------------------------------------------------------------


# Modify this path to specify where your .yaml files reside

game_yaml_dir: ../../reborn/DataExport

#-------------------------------------------------------------------------------
#  Miscellaneous Parameters
#-------------------------------------------------------------------------------

# This parameter determines whether the extra map files are deleted or left alone.
#   Valid values:  [true || false]
delete_other_maps: true

# This parameter determines whether the import/export scripts print verbose
# information such as each filename as it is imported or exported and timing
# information.  Errors are always printed.
#   Valid values:  [true || false]
verbose: false

